<img src="https://pandas.pydata.org/static/img/pandas.svg" width="250">

## <center> Pandas Options

In [3]:
import os
os.chdir('C:\\Users\\jenny\\venvs\\py39\\Lib\\site-packages')
import pandas as pd

In [4]:
emissions = pd.DataFrame({"country":['China','United States','India'],
          "year":['2018','2018','2018'],
          "co2_emissions":[10060000000.0, 5410000000.0, 2650000000.0]})

In [5]:
emissions

         country  year  co2_emissions
0          China  2018   1.006000e+10
1  United States  2018   5.410000e+09
2          India  2018   2.650000e+09

In [6]:
pd.set_option('max_rows', 2)
emissions

   country  year  co2_emissions
0    China  2018   1.006000e+10
..     ...   ...            ...
2    India  2018   2.650000e+09

[3 rows x 3 columns]

In [7]:
pd.set_option('max_columns', 2)
emissions

   country  ... co2_emissions
0    China  ...  1.006000e+10
..     ...  ...           ...
2    India  ...  2.650000e+09

[3 rows x 3 columns]

In [14]:
pd.options.display.float_format = '{:.2f}'.format

In [15]:
emissions

   country  ...  co2_emissions
0    China  ... 10060000000.00
..     ...  ...            ...
2    India  ...  2650000000.00

[3 rows x 3 columns]